### PR TITLE
lazy shard io

### PR DESCRIPTION
**Pull request by nlhepler**
Please review, but let's hold off testing until I can put it through its paces :D

### CODE REVIEW

**Comment by pmarks** [comment]
@nlhepler cool! Only other question is the perf impact of this change -- _hopefully_ this doesn't cause a bunch of problems

**Comment by nlhepler** [comment]
In criterion benchmarking, it does seem to regress performance by ~20% :(

**Comment by nlhepler** [comment]
Weirdly, writing is a bit slower too. ~8% so.

**Comment by nlhepler** [comment]
Varying the parameters a bit (4x bigger dataset, 2x larger chunksize), I got another result: 27% regression in read, 14% regression in write. <sigh>

I'm not surprised, but I was hoping it would have less of an impact.

Real-world perf test coming up next.

**Comment by nlhepler** [comment]
real-world testing is even stranger:
for the following stages, I computed the lazy-io / eager-io walltime duration ratio, and am reporting the [0, 25, 50, 75, and 100]th percentiles:

SHARD_READS (convert read-pairs in FASTQs to DnaRead objects): [0.25, 0.94, 1.03, 1.05, 3.64]
ALIGN_READS (align reads, DnaRead -> htslib::Record): [0.78, 1.01, 1.02 1.06, 1.25]
MARK_DUPS (just set the is_duplicate flag, record some stats, return to disk): [0.92, 0.96, 0.99, 1.01, 1.29]

So the picture here is not so clear-cut as the synthetic tiny benchmarks. I don't see a problem here, nothing is being dramatically slowed down. The only weird one is SHARD_READS, where I ran the whole set multiple times (because of various huge speedups/slowdowns), and I think the result is too dependent on the properties of the NFS transfer between our storage and the hydra compute node--sometimes taking 3 minutes, other times 8 minutes, and in one instance, >50 minutes.

Let me know if you require/desire more benchmarking, (or would like to have ShardReader have an internal buffering parameter (builder pattern) but I without this change I see uncontrollable memory usage dependent on the properties of the data.

**Pull request merged**
